# -*- coding: utf-8 -*-
"""Python and its common uses

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Z6slz_HoOml5YjPvvD_P8F8YkDXffnS
"""

print("Hello world")
print('Hello coders!')

print("Hello world")

var1 = 5
var2 = 19.54
var3 = "I am python"
var4 = True
#  This is a comment.
# we don't have to declare variable type in pyhton,

print(type(var1))
print(type(var2))
print(type(var3))
print(type(var4))

a = 5
b = 6
a+b

st = "Gautam"
st

# taking input using input()

# input()

a = 5

name = input("What is your name ?")
print(name)
print("Hello"+name)
age = input()
# age_new=age+2

age_new = int(age)+2  # Typecasting
print(age_new)

first = input("enter first number")
second = input("enter second number")

sum = int(first)+int(second)

sum

d = True

if d:
    print("True")
else:
    print("False")

age = 21

if age >= 18:
    print("You can vote")
elif age < 18 and age > 3:
    print("You are in school")
    print("ddbshbfd")
    print("hjdhbsd")

print("hsdhd")

print("Thank You")

# Lets make a calculator
a = input()
b = input()

# * / - + %

print('''"we are 'iitians"''')  # Python accepts single ('), double (") and triple (''' or """) quotes.

# STRINGS
name = "Gautam Bansal"
name2 = "Tony stark"

name3 = name.upper()

print(name.upper())
print(name)

# input()
# print()
# find()

print(name.find('B'))  # Give a conclusion
print(name.find('bansal'))  # Returns starting index of string

print(name.replace("Gautam", "XYZ"))
print(name2.replace("T", "M"))
print(name)

print("Gautam" in name)

# operators
print(5*2)
print(5/3)

print(5//3)

print(5 % 2)
print(5**2)

# # i=i+1

# # i+=1

# # # += -= ....... same as C
# # precedence

print(5*2+3)

print(3 < 2)
print(3 != 2)

# and or not

numbers = range(5)
for num in numbers:  # now this prints all the numbers in range(5)
    print(num)


# Loops
print(1)
print(2)
print(3)
print(4)
print(5)


i = 1
while i <= 5:
    print(i)
    i = i+1

while i <= 5:
    print(i*"*")
    i = i+1

# for

A = [[12, 7, 3],                      # int arr[]={{1,2,3}, {}}
     [4, 5, 6],
     [7, 8, 9]]

B = [[5, 8, 1, 2],
     [6, 7, 3, 0],
     [4, 5, 9, 1]]

result = [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]

# iterating by row of A
for i in range(len(A)):

    # iterating by column by B
    for j in range(len(B[0])):

        # iterating by rows of B
        for k in range(len(B)):

            result[i][j] += A[i][k] * B[k][j]

for r in result:
    print(r)

marks = [89, 78, 45, 99, 58, 67]
print(marks)
print(marks[1])
print(marks[1:8])


for score in range(len(marks)):
    print(marks[score])

print(55 in marks)

marks.append(55)

print(55 in marks)

# len returns the length of array
print(len(marks))

marks.clear()

# continue and break statements are same as C
